Batched inference CEBRA & padding at the `Solver` level
AdaptiveMotorControlLab/CEBRA pull request #168
Opened 2024-08-23 12:01 UTC by CeliaBenquet

fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/746

fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/624
fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/637
https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/594

2024-09-18 09:08 UTC, CeliaBenquet commented
@stes @MMathisLab, if you have time to review this that would be great :)

2024-09-18 09:10 UTC, MMathisLab approved these changes
this looks fine to me, and is already used internally in production right @stes ?

2024-09-18 09:11 UTC, MMathisLab commented
@CeliaBenquet can you solve the conflicts, then I think fine to merge!

2024-09-18 11:55 UTC, CeliaBenquet commented
@MMathisLab there's been big code change / refactoring since @stes's last review, so I would be more confident about merging after an "in-depth" reviewing, but your call :)

2024-09-18 12:47 UTC, stes commented
reviewing now

2024-09-18 13:04 UTC, stes requested changes
Left a few comments.

The biggest issue I see, is that a lot of features are changed that do not seem to be directly related to the batched implementation (but I might be wrong). So one iteration addressing some of these Qs in my review would help me understand the logic a bit better.

2024-09-18 13:12 UTC, CeliaBenquet commented on cebra/solver/base.py
> +    def save(self, logdir, filename="checkpoint.pth"):
Is there a reason it's different from the default in the load function?

2024-09-18 13:16 UTC, CeliaBenquet commented
re your comment on changes not related to the batched inference, it is because the PR was started with 2 (related) goals at once if I'm correct (not me who started it):
- batched inference, 
- but to do that in the solver, all padding etc operations in the transform needed to be moved from the cebra.CEBRA() class to the solver.

--> see other linked issues for better understanding.

2024-09-18 20:48 UTC, stes commented
Ok, makes sense!

2024-09-19 08:18 UTC, CeliaBenquet commented on cebra/data/base.py
>          self.offset = model.get_offset()
configure_for was done in the cebra.CEBRA class (in configure_for_all) and now it is moved to the solvers directly, and the configure_for in the multisession solver was wrongly implemented and not used.

So now not implemented in the base class and defined in multi and single solvers.

2024-09-19 08:21 UTC, CeliaBenquet commented on cebra/integrations/sklearn/cebra.py
> +        if torch.is_tensor(X) and X.device.type == "cuda":
changed

2024-09-19 08:24 UTC, CeliaBenquet commented on cebra/integrations/sklearn/cebra.py
> +            X = X.detach().cpu()
changed

2024-09-19 08:38 UTC, CeliaBenquet commented on cebra/integrations/sklearn/cebra.py
> +                  batch_size: Optional[int] = None,
done

2024-09-19 08:46 UTC, CeliaBenquet commented on cebra/solver/multi_session.py
> +            yield parameter
Not sure I get it, you mean we should return the parameters from the criterion at least? or the parameters for all models?

2024-09-19 10:12 UTC, CeliaBenquet commented on cebra/integrations/sklearn/cebra.py
> -            return output.astype(input_dtype)
done, see in `test_sklearn` if that's satisfying.

2024-09-19 10:13 UTC, CeliaBenquet commented on cebra/solver/base.py
> -            yield parameter
because doesn't apply to multi session class.

2024-09-19 10:33 UTC, CeliaBenquet commented on cebra/solver/base.py
> +                "appropriate arguments before using this estimator.")
that's what was done initially with the sklearn function.

I'm not sure to understand how the is_fitted changes that, it's just an implementation thing right? I keep the n_features? Another way could be to check if `history` is empty for instance.

2024-09-27 10:04 UTC, CeliaBenquet commented on docs/source/conf.py
> +    "torch": ("https://pytorch.org/docs/stable/", None),
see #176  :)

2024-10-20 15:22 UTC, stes commented
also upgraded this, and checking again once tests passed.

2025-01-21 23:04 UTC, stes commented
note, update to main first after #212 is merged

2025-01-21 23:10 UTC, stes commented
This error needs to be fixed in the usage.rst

![image](https://github.com/user-attachments/assets/f35e9f4b-d618-4e8e-85f1-2d231899b287)

2025-01-22 08:15 UTC, CeliaBenquet commented
Need to add corner case when input is shorter than 2 batches and batch inference is asked. 

Sol: either raise an error or go back to normal inference without telling the user as likely that memory won’t be an issue in that case

2025-02-18 09:51 UTC, MMathisLab commented
@CeliaBenquet @stes what else is needed for this? seems a conflict, then? tests issue?

2025-04-23 05:04 UTC, MMathisLab commented
Hey @CeliaBenquet can you resolve conflicts, then we can merge since this is internally in use!

2025-04-23 16:50 UTC, MMathisLab commented
```
=========================== short test summary info ============================
ERROR tests/test_benchmark.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_benchmark.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_benchmark.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_data_helper.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_data_helper.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_data_helper.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_datasets.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_datasets.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_datasets.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_distributions.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_distributions.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_distributions.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_integration_train.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_integration_train.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_integration_train.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_solver.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_solver.py - NameError: name 'get_datapath' is not defined
ERROR tests/test_solver.py - NameError: name 'get_datapath' is not defined
ERROR cebra/config.py - NameError: name 'get_datapath' is not defined
ERROR cebra/config.py - NameError: name 'get_datapath' is not defined
!!!!!!!!!!!!!!!!!!! Interrupted: 20 errors during collection !!!!!!!!!!!!!!!!!!!

2025-04-24 09:30 UTC, stes reviewed
some early comments; apologies if i have asked some of these before

2025-04-24 09:30 UTC, stes commented on tests/test_solver.py
> +    loader = _get_loader(data, loader_initfunc)
why the changes here? i.e. did anything change that would cause the "old" multi session tests to break?

2025-04-24 09:30 UTC, stes commented on tests/test_solver_batched.py
> +                (*args, cebra.solver.MultiSessionSolver))
can you wrap the for loops here (quite complex) in functions, and only do the assingment on the global level?

2025-04-24 09:30 UTC, stes commented on tests/test_solver_batched.py
> +                    (*args, cebra.solver.SingleSessionHybridSolver))
same here; also is there overlap to the functions above? i.e. could we unify all of these, is there a logic?

2025-04-24 09:30 UTC, stes commented on tests/test_solver_batched.py
> +                    (*args, cebra.solver.MultiSessionSolver))
same here

2025-04-24 09:30 UTC, stes commented on tests/test_solver_batched.py
> +    assert np.allclose(embedding_batched, embedding, rtol=1e-02)
quite high tolerence --- possible to make smaller?

2025-04-24 09:30 UTC, stes commented on tests/test_solver_batched.py
> +        assert np.allclose(embedding_batched, embedding, rtol=1e-02)
see above, high tolerance

2025-04-24 09:30 UTC, stes commented on cebra/data/base.py
> +        raise NotImplementedError
this seems like a potentially breaking change --- I think we discussed this before, but which function would break if we kept the `self.offset = model.get_offset()` logic here?

2025-04-24 09:30 UTC, stes commented on cebra/solver/single_session.py
> +    ) -> Tuple[Union[List[torch.nn.Module], torch.nn.Module],
there is no session ID here, right? if this is the only way to do it, raise a ValueError if the session ID is different than 0, plus add a default value.

is this _select_model also in the base class now as an abstract method?

2025-04-24 09:30 UTC, stes commented on cebra/solver/multiobjective.py
> +    def transform_deprecated(self, inputs: torch.Tensor) -> torch.Tensor:
this needs a longer comment on the rationale, I think; plus the function should raise some kind of error message or warning when called

2025-04-24 09:30 UTC, stes commented on cebra/solver/multiobjective.py
> +
why do we need a session_id here?

2025-04-24 09:50 UTC, CeliaBenquet commented on tests/test_solver.py
> +    loader = _get_loader(data, loader_initfunc)
I restablished _get_loader as it was.

Else,
- I added the model_architecture as offset1-model is a special case for padding at transform.
- I added the configure_for(model) as now this is handled in the solver.
- I added some tests on the transform (was not done at all before), similar to the sklearn tests but at the pytorch level.

2025-04-24 09:52 UTC, CeliaBenquet commented on tests/test_solver_batched.py
> +    assert np.allclose(embedding_batched, embedding, rtol=1e-02)
True, changed to be `rtol=1e-5, atol=1e-8`, similar to the sklearn tests.

2025-04-24 09:54 UTC, MMathisLab commented
doc error is: `/home/runner/work/CEBRA/CEBRA/cebra/data/single_session.py:docstring of cebra.data.single_session.SingleSessionDataset.configure_for:3: WARNING: py:attr reference target not found: cebra_data.Dataset.offset
/home/runner/work/CEBRA/CEBRA/cebra/data/multi_session.py:docstring of cebra.data.multi_session.MultiSessionDataset.configure_for:3: WARNING: py:attr reference target not found: cebra_data.Dataset.offset`

2025-04-24 09:55 UTC, CeliaBenquet commented on cebra/data/base.py
> +        raise NotImplementedError
I can revert, and redefine in multisession classes only.

2025-04-24 09:58 UTC, CeliaBenquet commented on cebra/solver/single_session.py
> +    ) -> Tuple[Union[List[torch.nn.Module], torch.nn.Module],
yes it's abstract method in base.

I can change this so that it just doesn't consider the session id provided, as it doesn't matter, I think I kept that because we were doing that in the CEBRA class before directly (and have the corresponding tests for it).

2025-04-24 11:02 UTC, CeliaBenquet commented on tests/test_solver_batched.py
> +                (*args, cebra.solver.MultiSessionSolver))
I proposed something lmk if that's what you meant :)

2025-04-24 11:02 UTC, CeliaBenquet commented on tests/test_solver_batched.py
> +                    (*args, cebra.solver.SingleSessionHybridSolver))
see above.

2025-04-24 15:17 UTC, MMathisLab commented
@CeliaBenquet not sure I see your edits post review; did you push them?

2025-04-25 17:07 UTC, stes reviewed
Left some initial comments; broader discussion is a bit on the api design in the solver/base class --- lets discuss offline.

2025-04-25 17:07 UTC, stes commented on cebra/solver/base.py
> +    """Check that indexes in a batch are in a correct range.
```suggestion
    """Check that indices in a batch are in a correct range.
```

2025-04-25 17:07 UTC, stes commented on cebra/solver/single_session.py
> +            offset = None
are there models without offsets?

2025-04-25 17:07 UTC, stes commented on tests/test_solver.py
> -                                                     10)
why weaken the test? specify last dim here as before

2025-04-25 17:07 UTC, stes commented on tests/test_solver.py
>      solver.fit(loader)
why drop the test

2025-04-25 17:17 UTC, CeliaBenquet commented on tests/test_solver.py
>      solver.fit(loader)
because it is completely similar to the first part of the above test `test_multi_session`.

2025-04-25 17:49 UTC, CeliaBenquet commented on cebra/integrations/sklearn/cebra.py
>                      f"got X:{len(X)} and y:{[len(y_i) for y_i in y]}.")
that was the existing code @stes I only removed the f" because I was getting a ruff error when running the pre-commit :)

2025-04-25 17:51 UTC, CeliaBenquet commented on cebra/integrations/sklearn/cebra.py
> +        """Transform an input sequence and return the embedding.
only for testing, so yes will move then, same for the transform method in xCEBRA then

2025-04-25 18:09 UTC, CeliaBenquet commented on tests/test_solver.py
> -                                                     10)
reverted.

2025-04-25 18:10 UTC, CeliaBenquet commented on cebra/solver/single_session.py
> +            offset = None
removed

2025-04-25 18:41 UTC, CeliaBenquet commented on cebra/data/multi_session.py
> +    def configure_for(self, model: "cebra.models.Model"):
I don't fully get your comment, but reverted to the original code, while adding the docstrings so should be no issue.

2025-05-01 14:17 UTC, MMathisLab approved these changes

2025-05-01 16:07 UTC, stes requested changes
Ok, review got a bit longer again; I realized I missed a few things on the last review. High level comments:

- I made some comments in solver which could be fine; I think some arguments were moved from the sklearn class to the solver class, but the motivation for that is not entirely clear. Mostly needs one round of discussion so we can settle on a good API design for these. Specifically, what is the usecase for storing these variables now in the solver, where are they called?
- the new `transform` function adds a lot of **duplicated code** that should be unified; again, could be first discussed

2025-05-01 16:07 UTC, stes commented on cebra/solver/single_session.py
> +        self.n_features = loader.dataset.input_dimension
this ties to the Q above --- why is this not simply a `@property`?

2025-05-01 16:07 UTC, stes commented on cebra/solver/single_session.py
> +    ) -> Tuple[Union[List[torch.nn.Module], torch.nn.Module],
From how I read the code now, for single session the session ID `None` is used, correct? shouldnt that then be the right one to put here, and raise an error if a different one is specified?

2025-05-01 16:07 UTC, stes commented on cebra/solver/single_session.py
> +                                     pad_before_transform=pad_before_transform)
code duplication? or what here is specific to the aux solver

2025-05-01 16:07 UTC, stes commented on cebra/solver/single_session.py
> +            inputs, session_id, use_reference_model=use_reference_model)
code duplication

2025-05-01 16:07 UTC, stes commented on cebra/solver/single_session.py
> +class SingleSessionHybridSolver(abc_.MultiobjectiveSolver, SingleSessionSolver):
This does not work, I think. Both inherit from `Solver` base, this might have some weird effects; what was the motivation though?

2025-05-01 16:07 UTC, stes commented on tests/test_integration_xcebra.py
> +import _utils_deprecated
multiobjective is tested, single objective is not

2025-05-01 16:07 UTC, stes commented on tests/test_solver.py
> +def test_single_session(data_name, loader_initfunc, model_architecture,
this test exploded; can we modularize further?

2025-05-02 13:52 UTC, CeliaBenquet commented on cebra/solver/single_session.py
> +class SingleSessionHybridSolver(abc_.MultiobjectiveSolver, SingleSessionSolver):
it's the same transform() method as well as all the checks methods etc. so that's to avoid a lot of duplicate code. 

I thought so as well but all tests pass, and they don't have redefined methods in common. Else happy to hear your suggestion to avoid duplication.

2025-05-02 14:09 UTC, CeliaBenquet commented on cebra/solver/single_session.py
> +        self.n_features = loader.dataset.input_dimension
because that depends on the loader/inputs to the fit() and can be updated if the solver is adapted.

2025-05-02 14:30 UTC, CeliaBenquet commented on cebra/solver/base.py
> +                batch_size * 2) and not isinstance(
That's to handle the last batch that can be incomplete and that we concatenate to the previous batch (see #200).

else we get an error like that: `ValueError: batch_end_idx (1019) cannot exceed the length of inputs (1000).`

2025-05-02 14:42 UTC, CeliaBenquet commented on cebra/solver/base.py
> +            state_dict["n_features"] = self.n_features
for the multisession case that's already the case and that's a list.

`num_features` cannot be a property I think, because that can be defined only based on the inputs provided to the fit(), and later if we adapt the solver, it needs to be reset. This is used to be saved with the solver as it's needed when reloading it + to be called in the sklearn.

2025-05-02 14:46 UTC, CeliaBenquet commented on cebra/solver/multi_session.py
> +                yield parameter
raise an error now.

2025-05-02 14:59 UTC, CeliaBenquet commented on cebra/solver/base.py
> +            state_dict["num_sessions"] = self.num_sessions
removed for single session solvers. this is needed in multi session solvers to assess session_id validity.

2025-05-06 09:35 UTC, stes commented on cebra/solver/single_session.py
> +class SingleSessionHybridSolver(abc_.MultiobjectiveSolver, SingleSessionSolver):
What are the methods that would be duplicated, could you list here, @CeliaBenquet ? If this is the issue, the proper way is that we write a `Mixin` functionality that puts the otherwise duplicated functions with same functionality in a new class.

2025-05-06 09:36 UTC, stes commented on cebra/solver/base.py
> +        ] if isinstance(n_features, list) else n_features)
@CeliaBenquet ping

2025-05-06 09:37 UTC, stes commented on cebra/solver/single_session.py
> +        self.n_features = loader.dataset.input_dimension
@CeliaBenquet are you sure this is the case?

- `n_features` relates directly to the input dimensionality of the `model`, which is already stored in the solver
- `num_sessions` relates to a property of the multi-session model (i.e., how many input layers are in the module list).

In scikit-learn, this is indeed all constructed when running the `fit()` method, but in the Solver, if you specify your model and it does not fit the dataset, this should raise an issue.

What am I missing, was this logic changed?

2025-05-06 09:38 UTC, stes commented on cebra/solver/base.py
> +        ] if isinstance(n_features, list) else n_features)
ok sorry, duplicate of https://github.com/AdaptiveMotorControlLab/CEBRA/pull/168#discussion_r2070450716, lets discuss there

2025-05-08 10:27 UTC, stes commented on cebra/solver/multiobjective.py
> +        super().parameters(session_id=session_id)
is this an error? this does not do anything besides checking, right? shouldnt the params be also returend?

2025-05-12 11:03 UTC, CeliaBenquet commented on tests/test_integration_xcebra.py
> +import _utils_deprecated
single objective solver transform was not tested before that PR + not used in the CEBRA() class, so we test the CEBRA transform (single objective) and the multiobjective one, as the solver transform was more similar to the new structure (padding, etc).

2025-05-12 13:08 UTC, stes commented on cebra/solver/single_session.py
> +class SingleSessionHybridSolver(abc_.MultiobjectiveSolver, SingleSessionSolver):
notes, but not final

``` python

class BaseSolverMixin(abc.ABC):

  # all abstract
  parameters
  _set_fitted_params
  _check_is_inputs_valid
  _check_is_session_id_valid


class SingleSessionMixin(BaseSolverMixin)
   ... 

class MultiSessionMixin(BaseSolverMixin)
   ... 

```

2025-05-23 08:58 UTC, CeliaBenquet commented on cebra/solver/multiobjective.py
> +        super().parameters(session_id=session_id)
it returns the parameters and the criterion from single session solver method no?

2025-05-23 13:35 UTC, MMathisLab commented
At the risk of it not being perfect, lets merge this now; @CeliaBenquet can document in an issue the remaining Qs on the API design, but getting #251 merged is a priority 🦾

2025-05-23 13:37 UTC, MMathisLab approved these changes

2025-05-23 13:38 UTC, merged