Set default offset to an Offset object
AdaptiveMotorControlLab/CEBRA pull request #180
Opened 2024-10-16 05:04 UTC by icarosadero

Should fix #175

2024-10-16 05:06 UTC, icarosadero commented
@cla-bot check

2024-10-26 16:03 UTC, stes requested changes
@icarosadero i think the offset here is actually not used, right? We could also consider deprecating the argument instead.

Do you have a code example that's fixed by this change?

2024-10-26 21:17 UTC, stes reviewed
set to `None` (unused)

2024-10-26 21:17 UTC, stes commented on cebra/data/datasets.py
> +                 offset: Offset = Offset(1),
```suggestion
                 offset: Offset = None,
```

2024-10-26 21:20 UTC, stes commented on cebra/data/datasets.py
> +                 offset: Offset = Offset(1),
```suggestion
                 offset: Offset = Offset(0, 1),
```

otherwise, a symmetric offset is chosen

2024-10-26 21:20 UTC, stes approved these changes

2024-10-26 21:21 UTC, stes commented
can be merged once tests pass

2024-10-26 21:21 UTC, stes requested changes
@icarosadero if you get the chance, could you add a test that reproduces this error https://github.com/AdaptiveMotorControlLab/CEBRA/issues/174#issue-2533087585 to this PR?

2024-10-27 13:35 UTC, stes approved these changes
Thanks for your contribution, @icarosadero , lgtm!

2024-10-27 13:36 UTC, merged