[WIP] Add improved goodness of fit implementation
AdaptiveMotorControlLab/CEBRA pull request #190
Opened 2024-10-27 17:02 UTC by stes

This adds a better goodness of fit measure. Instead of the old variant which simply matched the InfoNCE and depends on the batch size, the proposed measure

- is at 0 for "chance level" (vs. log batch size)
- does not need an adjustment for single session vs. multi-session solvers
- increases as the model gets better, which might be more intuitive

The conversion is quite simply done via

```
GoF(model) = log (batch_size_per_session * num_sessions) - InfoNCE(model)
```

This measure is also used in [DeWolf et al., 2024, Eq. (43)](https://www.biorxiv.org/content/10.1101/2024.09.11.612513v1)

![image](https://github.com/user-attachments/assets/93ba9e35-34d3-4df4-b90e-1d3ccb96326e)

Application example (GoF improves from 0 to a larger value during training):

![image](https://github.com/user-attachments/assets/b0572c85-792f-4e9d-9d23-bd62518fc206)

---

Close https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/669

2024-10-27 18:23 UTC, stes commented
TODO: Fix case where batch_size is `None`
![image](https://github.com/user-attachments/assets/a7bc6563-c34d-4291-9134-d308c2386f3d)

2024-11-29 13:41 UTC, CeliaBenquet commented
@stes about what I implemented in #202 that I do see here. 

I think it would be good to have a really basic function where you provide the loss and the batch size, so that it is easily usable in the pytorch implementation as well.

Also, it would be nice to test for the default `CEBRA.batch_size = None`, not sure it is handled here.

2024-12-16 17:09 UTC, stes commented on cebra/integrations/sklearn/metrics.py
> +        >>> cebra_model = cebra.CEBRA(max_iterations=10)
```suggestion
        >>> cebra_model = cebra.CEBRA(max_iterations=10, batch_size = 512)
```

2024-12-16 17:12 UTC, stes commented on cebra/integrations/sklearn/metrics.py
> +        raise RuntimeError("Fit the CEBRA model first.")
```suggestion
    if not hasattr(model, "state_dict_"):
        raise RuntimeError("Fit the CEBRA model first.")
    if model.batch_size is None:
        raise ValueError(
            "Computing the goodness of fit is not yet supported for "
            "models trained on the full dataset (batchsize = None). " 
        )
```

2024-12-16 17:39 UTC, stes commented
Unrelated build issue due to upstream change in sklearn (#204 ), attempted fix in #205

2024-12-16 18:30 UTC, stes commented
The build issue is fixed, and once #205 is merged tests should pass here as well.

2024-12-17 09:50 UTC, stes commented on cebra/integrations/sklearn/metrics.py
> +        CEBRA(max_iterations=10)
```suggestion
        CEBRA(batch_size=512, max_iterations=10)
```

2024-12-17 09:52 UTC, CeliaBenquet requested changes
Thank you @stes! This looks nice!! Some minor suggestions on the docstrings and maybe add some tests for the different corner cases based on the arguments provided in `infonce_to_goodness_of_fit`.

2025-01-24 23:14 UTC, stes commented on tests/test_sklearn_metrics.py
> +    np.testing.assert_allclose(history_random_non_negative, 0, atol=0.05)
```suggestion
    np.testing.assert_allclose(history_random_non_negative, 0, atol=0.075)
```

slightly less conservative threshold due to failed test

2025-01-25 00:33 UTC, stes commented
one review comment to resolve (= add more relevant tests for one batchsize None), then ready!

2025-02-02 16:58 UTC, MMathisLab approved these changes
lgtm! thanks

2025-02-02 16:59 UTC, merged