Fix deprecation warning force_all_finite -> ensure_all_finite for sklearn>=1.6
AdaptiveMotorControlLab/CEBRA pull request #206
Opened 2024-12-17 10:16 UTC by icarosadero

The current CEBRA branch raised the following deprecation message

```bash
FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
```

See the deprecation warning in the [docs](https://scikit-learn.org/dev/modules/generated/sklearn.utils.check_array.html)

This PR adds a wrapper to cebra/integrations/sklearn/utils.py which manually adapts the argument to `force_all_finite` if an outdated sklearn version is used.

(edited by @stes )

2024-12-17 10:28 UTC, stes commented
Hi @icarosadero , thanks a lot for fixing! Do you happen to know when the `ensure_all_finite` was introduced in scikit-learn and have a reference to the docs? As the code will require this as the new minimal version then to function, I guess?

2024-12-17 10:34 UTC, stes requested changes
ok so it seems that this is indeed an issue also for recent versions of scikit-learn:
<img width="842" alt="image" src="https://github.com/user-attachments/assets/3f796473-e278-4126-80f8-65bb97bb3156" />

If you want to take a try at solving this, have a look at e.g. this snippet of code https://github.com/AdaptiveMotorControlLab/CEBRA/blob/5f46c3257952a08dfa9f9e1b149a85f7f12c1053/cebra/integrations/sklearn/cebra.py#L46-L50

You could then implement a conditional part where the version is checked, and the arg is passed based on the version of sklearn.

2024-12-18 05:46 UTC, stes requested changes
I made a suggestion which is a bit more crisp and avoids code duplication

2024-12-18 05:46 UTC, stes commented on cebra/integrations/sklearn/utils.py
> +
```suggestion
from packaging import version
import sklearn

def _check_array_ensure_all_finite(array, **kwargs):
    if version.parse(sklearn.__version__) < version.parse("1.8"):
        key = "force_all_finite"
    else:
        key = "ensure_all_finite"
    kwargs[key] = True
    return sklearn_utils_validation.check_array(array, **kwargs)
```

2024-12-18 05:46 UTC, stes commented on cebra/integrations/sklearn/utils.py
> +        )
```suggestion
    return _check_array_ensure_all_finite(
          X,
          accept_sparse=False,
          accept_large_sparse=False,
          dtype=("float16", "float32", "float64"),
          order=None,
          copy=False,
          ensure_2d=True,
          allow_nd=False,
          ensure_min_samples=min_samples,
          ensure_min_features=1,
      )
```

2024-12-18 05:46 UTC, stes commented on cebra/integrations/sklearn/utils.py
> +        )
```suggestion
    return _check_array_ensure_all_finite(
        y,
        accept_sparse=False,
        accept_large_sparse=False,
        dtype="numeric",
        order=None,
        copy=False,
        ensure_2d=False,
        allow_nd=False,
        ensure_min_samples=min_samples,
    )
```

2024-12-18 05:48 UTC, stes commented
could you also update the PR description with the reference to the docs, pointing that this API change happend from 1.7.x to 1.8.x?

2025-01-21 22:27 UTC, stes approved these changes
lgtm (wait with merge until #212 is merged, though)

2025-01-21 23:54 UTC, stes reviewed
one final change, the threshold to fix the arg is 1.6, not 1.8

2025-01-21 23:54 UTC, stes commented on cebra/integrations/sklearn/utils.py
> +            sklearn.__version__) < packaging.version.parse("1.8"):
```suggestion
    # NOTE(stes): See discussion in https://github.com/AdaptiveMotorControlLab/CEBRA/pull/206
    # https://scikit-learn.org/1.6/modules/generated/sklearn.utils.check_array.html
    # force_all_finite was renamed to ensure_all_finite and will be removed in 1.8.
    if packaging.version.parse(
            sklearn.__version__) < packaging.version.parse("1.6"):
```

2025-01-22 00:29 UTC, stes approved these changes
all right, final from my end

2025-01-22 06:51 UTC, MMathisLab reviewed
Lgtm; did not functionally test

2025-01-22 06:51 UTC, MMathisLab approved these changes

2025-01-22 06:52 UTC, merged